INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (1, 'Adventure');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (2, 'Drama');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (3, 'Science Fiction');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (4, 'War');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (6, 'Comedy');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (7, 'Animation');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (8, 'Family');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (9, 'Fantasy');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (10, 'Action');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (11, 'Crime');
INSERT INTO team9.MovieGenre (GenreID, GenreName) VALUES (12, 'Thriller');
